# This is a basic workflow to help you get started with Actions

name: frontend Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
    paths:
      - frontend/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_KEY: AIzaSyDwtUzkUtohwgG9up1enBLuB8hGTSZhBBg
      REACT_APP_AUTH_DOMAIN: bmd-attendance.firebaseapp.com
      REACT_APP_PROJECT_ID: bmd-attendance
      REACT_APP_STORAGE_BUCKET: bmd-attendance.appspot.com
      REACT_APP_MESSAGING_SENDER_ID: 570247329292
      REACT_APP_ID: 1:570247329292:web:af5b5b2618215c39396029
      REACT_APP_GET_ATTENDANCE_API: https://glacial-plains-77487.herokuapp.com/getattendance
      REACT_APP_CREATE_ATTENDANCE_API: https://glacial-plains-77487.herokuapp.com/createAttendance
      REACT_APP_LOGIN_API: https://glacial-plains-77487.herokuapp.com/login

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install node version 12
      - name: Installing Nodejs
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Installing Frontend dependencies
        run: cd frontend && yarn install

      - name: Build Application
        run: cd frontend && CI='' npm run build

        # Installs Surge
      - name: Install surge
        run: sudo npm install -g surge

        # Deploys to Surge
      - name: Deploy to surge
        run: cd frontend && surge ./build web3-redux-typescript-byahsen.surge.sh --token ${{ secrets.SURGE_TOKEN }}
