# This is a basic workflow to help you get started with Actions

name: frontend Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
    paths:
      - frontend/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_KEY: ${{secrets.REACT_APP_API_KEY}}
      REACT_APP_AUTH_DOMAIN: ${{secrets.REACT_APP_AUTH_DOMAIN}}
      REACT_APP_PROJECT_ID: ${{secrets.REACT_APP_PROJECT_ID}}
      REACT_APP_STORAGE_BUCKET: ${{secrets.REACT_APP_STORAGE_BUCKET}}
      REACT_APP_MESSAGING_SENDER_ID: ${{secrets.REACT_APP_MESSAGING_SENDER_ID}}
      REACT_APP_ID: ${{secrets.REACT_APP_ID}}
      REACT_APP_GET_ATTENDANCE_API: ${{secrets.REACT_APP_GET_ATTENDANCE_API}}
      REACT_APP_CREATE_ATTENDANCE_API: ${{secrets.REACT_APP_CREATE_ATTENDANCE_API}}
      REACT_APP_LOGIN_API: ${{secrets.REACT_APP_LOGIN_API}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install node version 12
      - name: Installing Nodejs
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      # --force flag is not necessary. Dont use it unless there's a specific reason
      - name: Installing Frontend dependencies
        run: cd frontend && npm install --force  

      - name: Build Application
        run: cd frontend && CI='' npm run build

        # Installs Surge
      - name: Install surge
        run: sudo npm install -g surge

        # Deploys to Surge
      - name: Deploy to surge
        run: cd frontend && surge ./build attendance-app-byahsen.surge.sh --token ${{ secrets.SURGE_TOKEN }}
